<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <RootNamespace>RakionServer.Peer</RootNamespace>
    <AssemblyName>RakionServer.Peer</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RakionServer.Common\RakionServer.Common.csproj" />
  </ItemGroup>

</Project>
